name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - name: Claude Code GitHub Action
        uses: anthropic/claude-github-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
